# language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t arrcher/docker-react -f Dockerfile.dev .


script:
  # - docker run arrcher/docker-react npm run test -- --coverage
  - docker run -e CI=true arrcher/docker-react npm run test
