FROM node:alpine

# provided by caller
ARG proxy_http 
ARG HTTP_PROXY=$proxy_http
ARG HTTPS_PROXY=$proxy_http
ARG http_proxy=$proxy_http
ARG https_proxy=$proxy_http

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY ./ ./

CMD ["npm", "run", "start"]
